FROM php:8.1-cli

# Install dependencies Laravel but simpel
RUN apt-get update && apt-get install -y \
    unzip \
    libzip-dev \
    zip \
    && docker-php-ext-install zip pdo_mysql

# Install Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html

# Copy source code (optional, kalo mau build image langsung)
# COPY . .

CMD ["sh", "-c", "composer install && php artisan key:generate && php artisan serve --host=0.0.0.0 --port=8000"]
